In [1]:
#importing libraires

import pandas as pd

In [2]:
#loading dataset

dataset = pd.read_csv('dataset.csv')
dataset = dataset.drop(['car_ID'],axis=1)

In [3]:
#summarizing dataset

print(dataset.shape)
print(dataset.head(5))

(205, 25)
   symboling                   CarName fueltype aspiration doornumber  \
0          3        alfa-romero giulia      gas        std        two
1          3       alfa-romero stelvio      gas        std        two
2          1  alfa-romero Quadrifoglio      gas        std        two
3          2               audi 100 ls      gas        std       four
4          2                audi 100ls      gas        std       four

       carbody drivewheel enginelocation  wheelbase  carlength  ...  \
0  convertible        rwd          front       88.6      168.8  ...
1  convertible        rwd          front       88.6      168.8  ...
2    hatchback        rwd          front       94.5      171.2  ...
3        sedan        fwd          front       99.8      176.6  ...
4        sedan        4wd          front       99.4      176.6  ...

   enginesize  fuelsystem  boreratio stroke compressionratio  horsepower  \
0         130        mpfi       3.47   2.68              9.0         111
1         130        mpfi       3.47   2.68              9.0         111
2         152        mpfi       2.68   3.47              9.0         154
3         109        mpfi       3.19   3.40             10.0         102
4         136        mpfi       3.19   3.40              8.0         115

  peakrpm  citympg  highwaympg    price
0    5000       21          27  13495.0
1    5000       21          27  16500.0
2    5000       19          26  16500.0
3    5500       24          30  13950.0
4    5500       18          22  17450.0

[5 rows x 25 columns]

In [4]:
#splitting dataset into X and Y

Xdata = dataset.drop('price',axis='columns')
numericalCols=Xdata.select_dtypes(exclude=['object']).columns
X=Xdata[numericalCols]
X

Y = dataset['price']
Y

0      13495.0
1      16500.0
2      16500.0
3      13950.0
4      17450.0
        ...
200    16845.0
201    19045.0
202    21485.0
203    22470.0
204    22625.0
Name: price, Length: 205, dtype: float64

In [5]:
#scaling the Independent Variables (Features)


from sklearn.preprocessing import scale
cols = X.columns
X = pd.DataFrame(scale(X))
X.columns = cols
X

,symboling,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg
0,1.743470,-1.690772,-0.426521,-0.844782,-2.020417,-0.014566,0.074449,0.519071,-1.839377,-0.288349,0.174483,-0.262960,-0.646553,-0.546059
1,1.743470,-1.690772,-0.426521,-0.844782,-2.020417,-0.014566,0.074449,0.519071,-1.839377,-0.288349,0.174483,-0.262960,-0.646553,-0.546059
2,0.133509,-0.708596,-0.231513,-0.190566,-0.543527,0.514882,0.604046,-2.404880,0.685946,-0.288349,1.264536,-0.262960,-0.953012,-0.691627
3,0.938490,0.173698,0.207256,0.136542,0.235942,-0.420797,-0.431076,-0.517266,0.462183,-0.035973,-0.053668,0.787855,-0.186865,-0.109354
4,0.938490,0.107110,0.207256,0.230001,0.235942,0.516807,0.218885,-0.517266,0.462183,-0.540725,0.275883,0.787855,-1.106241,-1.273900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1.476452,1.721873,1.198549,1.398245,0.728239,0.763241,0.339248,1.666445,-0.336970,-0.162161,0.250533,0.577692,-0.340094,-0.400490
201,-1.476452,1.721873,1.198549,1.351515,0.728239,0.949992,0.339248,1.666445,-0.336970,-0.364062,1.416637,0.367529,-0.953012,-0.837195
202,-1.476452,1.721873,1.198549,1.398245,0.728239,0.878757,1.109571,0.926204,-1.232021,-0.338824,0.757535,0.787855,-1.106241,-1.128332
203,-1.476452,1.721873,1.198549,1.398245,0.728239,1.273437,0.435538,-1.183483,0.462183,3.244916,0.047732,-0.683286,0.119594,-0.546059
204,-1.476452,1.721873,1.198549,1.398245,0.728239,0.975021,0.339248,1.666445,-0.336970,-0.162161,0.250533,0.577692,-0.953012,-0.837195

In [6]:
#splitting dataset into Train and Test

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.20,random_state=0)

In [7]:
#traing using Random Forest

from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor()
model.fit(x_train, y_train)

RandomForestRegressor()

In [8]:
#Evaluating Model

ypred = model.predict(x_test)

from sklearn.metrics import r2_score
r2score = r2_score(y_test,ypred)
print("R2Score",r2score*100)

R2Score 89.90537581897522